//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buyer
    {
        public Buyer()
        {
            this.Bill = new HashSet<Bill>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string LName { get; set; }
        public string MName { get; set; }
        public string Adress { get; set; }
        public Nullable<int> DiscountNuber { get; set; }
    
        public virtual ICollection<Bill> Bill { get; set; }
    }
}
