//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cathegory
    {
        public Cathegory()
        {
            this.CathegoryProduct = new HashSet<CathegoryProduct>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CathegoryProduct> CathegoryProduct { get; set; }
    }
}
