//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.CathegoryProduct = new HashSet<CathegoryProduct>();
            this.ProductProducer = new HashSet<ProductProducer>();
            this.Sales = new HashSet<Sales>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<bool> Garanty { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> StocksQty { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CathegoryProduct> CathegoryProduct { get; set; }
        public virtual ICollection<ProductProducer> ProductProducer { get; set; }
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
