//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductProducer
    {
        public int ID { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Producerid { get; set; }
    
        public virtual Producer Producer { get; set; }
        public virtual Product Product { get; set; }
    }
}
