//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public Sales()
        {
            this.Bill = new HashSet<Bill>();
        }
    
        public int ID { get; set; }
        public string Number { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> SalesQty { get; set; }
        public System.DateTime DalesDate { get; set; }
    
        public virtual ICollection<Bill> Bill { get; set; }
        public virtual Product Product { get; set; }
    }
}
